package mytool

import (
	"blockEmulator/core"
	"sync"
)

var (
	UserRequestB2EQueue   []*core.Transaction
	AutoGeneratedB2EQueue []*core.Transaction
	Mutex                 sync.Mutex
	Mutex1                sync.Mutex

	Nonce  uint64
	Mutex2 sync.Mutex
)
